# Generated by Django 4.1.13 on 2026-02-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratedDetectionLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_ip', models.CharField(max_length=15)),
                ('detected_at', models.DateTimeField()),
                ('request_url', models.TextField()),
                ('domain', models.CharField(max_length=255)),
                ('http_method', models.CharField(max_length=7)),
                ('dst_port', models.IntegerField()),
                ('query_string', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'integrated_detection_logs',
                'managed': False,
            },
        ),
    ]
