# Generated by Django 4.1.13 on 2026-02-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=30)),
                ('policy_type', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('handling_type', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('create_by', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('delete_by', models.CharField(max_length=20)),
                ('delete_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'policy_delete_history',
                'managed': True,
            },
        ),
    ]
